### ISSUE TITLE
 what's the dataset you used to train the model?  

### ISSUE THREAD

**Issue by Egolee0713** [SHAHROHAN26/weapon-detection#1]
I can't find any dataset for weapons to train model, such as gun,  sword and knife. Can you tell me what's the dataset you used to train the model?

**Comment by SHAHROHAN26** [comment]
https://storage.googleapis.com/openimages/web/visualizer/index.html?set=train&type=detection&c=%2Fm%2F083kb

in above link you get detaset for weapons
